### PR TITLE
Add Apache 2.0 LICENSE

### PR DESCRIPTION
**Pull request by chartpath**
Currently it would be a copyright violation for community users to modify this repo because it is missing a license.

For comparison, the other popular Supabase GenAI community repo https://github.com/supabase-community/vercel-ai-chatbot is already using the Apache 2.0 license.

### CODE REVIEW

**Comment by chartpath** [comment]
BTW I just noticed Supabase uses Apache 2.0 for their main release so I figured that would be consistent in terms of choices. There seem to be a few other community projects that use MIT as well.

**Comment by chartpath** [comment]
For more reference on the rationale of why not having a license can be restrictive to contributors, see https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by gregnr** [comment]
Hey @chartpath, sorry for the delay on this. This is a good call - we've added the Apache 2.0 license now. I mistakenly thought this thread was an issue and not a PR, so merged the change in a separate PR #52. Sorry about that.

Thanks for the suggestion!

**Comment by chartpath** [comment]
@gregnr Thank you! This will allow me to make a contribution now :)

**Pull request closed without merging**
